# Generated by Django 4.2.5 on 2023-09-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thrift', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailpembelian',
            name='jumlah',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detailpenjualan',
            name='jumlah',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bal',
            name='kodeBAL',
            field=models.CharField(max_length=50),
        ),
    ]
